---
# tasks file for bluetooth

- name:            Install packages
  apt:             pkg={{ item }} state=present
  with_items:
    - bluetooth 
    - blueman
    - pi-bluetooth
    - pulseaudio-module-bluetooth 
    - python-gobject 
    - python-gobject-2
  become:          true

- name:            Add user to lp Group
  user: 
    name:  "{{  ansible_ssh_user }}"
    groups: lp
    append: yes
