---
- name:            Install packages
  apt:             pkg={{ item }} state=present
  with_items:
    - git 
    - zip
    - unzip
    - curl
    - jq
    - vim
    - screen
    - silversearcher-ag
    - zsh
    - m4
  become:          yes
